# Generated by Django 3.0.9 on 2020-10-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alllisting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
