# Generated by Django 3.0.9 on 2020-10-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20201023_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Closedbid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
    ]
